"""Unification tests: FAFB CAVE-skeletonized replacement store.

Covers the cave_skeletons store contract and the resolver convergence rule:
- `fetch_skeleton` persists level-0 trees with a `# DROCAT source:
  cave_mesh_wavefront` header in `cave_skeletons/` (never raw_skeletons/),
  with a read-only legacy fallback into the pre-unification raw-store
  location (level-0 entries only — simp90-legacy entries are ignored).
- `load_cached_skeleton` probes the dedicated store without network access.
"""

import io
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

import navis  # noqa: E402

import cave_data_fetcher as cdf  # noqa: E402
from cave_data_fetcher import (  # noqa: E402
    _load_swc_text,
    _read_stored_simplification,
    _read_stored_source,
    _write_compressed_swc_zst,
)

FAFB_ID_STR = "720575940622355894"


def _nodes_df(body_id=42, n_nodes=6):
    nodes = pd.DataFrame({
        "node_id": np.arange(n_nodes, dtype=np.int64),
        "parent": np.array([-1] + list(range(n_nodes - 1)), dtype=np.int64),
        "x": np.arange(n_nodes, dtype=float) * 1000.0,
        "y": np.zeros(n_nodes),
        "z": np.zeros(n_nodes),
        "radius": np.full(n_nodes, 50.0),
    })
    return nodes


def _tree(body_id=42):
    nrn = navis.TreeNeuron(_nodes_df(body_id))
    nrn.id = int(body_id)
    nrn.units = "nm"
    return nrn


def _swc_bytes(body_id=42, source=None):
    n = _nodes_df(body_id)
    lines = []
    if source:
        lines.append(f"# DROCAT source: {source}")
    lines.append("# SWC generated by test")
    lines.append("# node_id type x y z radius parent")
    for i in range(len(n)):
        lines.append(
            f"{int(n['node_id'][i])} 3 {n['x'][i]:.2f} {n['y'][i]:.2f} "
            f"{n['z'][i]:.2f} {n['radius'][i]:.2f} {int(n['parent'][i])}")
    return ("\n".join(lines) + "\n").encode("utf-8")


def _write_cave_store_entry(root, body_id_str="42"):
    store = (Path(root) / "cache" / "flywire_FAFB_v783"
             / "skeletons" / "cave_skeletons")
    store.mkdir(parents=True, exist_ok=True)
    path = store / f"{body_id_str}.swc.zst"
    _write_compressed_swc_zst(
        str(path), _swc_bytes(42, source="cave_mesh_wavefront"),
        simplification=0)
    return path


def _make_fetcher(tmp_path, **over):
    attrs = dict(dataset="flywire_FAFB_v783", cave_token="test-token",
                 cache_enabled=True, project_root=str(tmp_path),
                 verbose=False)
    attrs.update(over)
    return cdf.CAVEDataFetcher(**attrs)


class TestCaveSkeletonStore:
    def test_fetch_skeleton_writes_cave_store_never_raw_store(
            self, tmp_path, monkeypatch):
        fetcher = _make_fetcher(tmp_path)
        monkeypatch.setattr(fetcher, "fetch_mesh",
                            lambda _bid, use_cache=False: object())
        monkeypatch.setattr(cdf.navis, "skeletonize",
                            lambda *_a, **_k: _tree(42))

        assert fetcher.fetch_skeleton(42, use_cache=True) is not None

        cave_path = (tmp_path / "cache" / "flywire_FAFB_v783"
                     / "skeletons" / "cave_skeletons" / "42.swc.zst")
        raw_path = (tmp_path / "cache" / "flywire_FAFB_v783"
                    / "skeletons" / "raw_skeletons" / "42.swc.zst")
        assert cave_path.exists()
        assert not raw_path.exists()

        content = _load_swc_text(str(cave_path))
        assert _read_stored_simplification(content) == 0
        assert _read_stored_source(content) == "cave_mesh_wavefront"

    def test_store_hit_skips_the_mesh_fetch(self, tmp_path, monkeypatch):
        _write_cave_store_entry(tmp_path, body_id_str="42")
        fetcher = _make_fetcher(tmp_path)
        monkeypatch.setattr(
            fetcher, "fetch_mesh",
            lambda *_a, **_k: pytest.fail("store hit fetched the mesh"))

        neuron = fetcher.fetch_skeleton(42, use_cache=True)
        assert isinstance(neuron, navis.TreeNeuron)
        assert getattr(neuron, "_drocat_source", "") == "cave_mesh_wavefront"

    def test_load_cached_skeleton_probes_without_network(self, tmp_path):
        assert _write_cave_store_entry(tmp_path, body_id_str="42").exists()
        fetcher = _make_fetcher(tmp_path)
        neuron = fetcher.load_cached_skeleton(42)
        assert isinstance(neuron, navis.TreeNeuron)
        assert fetcher.load_cached_skeleton(999) is None

    def test_cache_stats_and_clear_cover_dedicated_store(self, tmp_path):
        fetcher = _make_fetcher(tmp_path)
        cave_path = _write_cave_store_entry(tmp_path, body_id_str="42")
        api_skeleton_dir = Path(fetcher.get_cache_path("skeletons"))
        api_skeleton_dir.mkdir(parents=True, exist_ok=True)
        (api_skeleton_dir / "legacy.pkl").write_bytes(b"legacy")

        stats = fetcher.get_cache_stats()
        assert stats["skeleton_count"] == 2

        fetcher.clear_cache("skeletons")

        assert not cave_path.exists()
        assert api_skeleton_dir.is_dir()
        assert not list(api_skeleton_dir.iterdir())
        canonical_skeleton_dir = (
            tmp_path / "cache" / "flywire_FAFB_v783" / "skeletons"
        )
        assert canonical_skeleton_dir.is_dir()
        assert not list(canonical_skeleton_dir.iterdir())

    def test_legacy_raw_store_level0_is_served(self, tmp_path):
        """Pre-unification raw-store entries stay readable (level 0 only)."""
        legacy_dir = (tmp_path / "cache" / "flywire_FAFB_v783"
                      / "skeletons" / "raw_skeletons")
        legacy_dir.mkdir(parents=True)
        _write_compressed_swc_zst(
            str(legacy_dir / "42.swc.zst"), _swc_bytes(42), simplification=0)

        fetcher = _make_fetcher(tmp_path)
        # The network-free probe reads the dedicated cave store only.
        assert fetcher.load_cached_skeleton(42) is None
        # But fetch_skeleton serves the legacy level-0 entry as a fallback.
        neuron = fetcher._load_pre_unification_raw_store_skeleton(42)
        assert isinstance(neuron, navis.TreeNeuron)

    def test_legacy_raw_store_simp90_is_rejected(self, tmp_path):
        """Historical simp90 visualization writes are not raw inputs."""
        legacy_dir = (tmp_path / "cache" / "flywire_FAFB_v783"
                      / "skeletons" / "raw_skeletons")
        legacy_dir.mkdir(parents=True)
        _write_compressed_swc_zst(
            str(legacy_dir / "42.swc.zst"), _swc_bytes(42), simplification=90)

        fetcher = _make_fetcher(tmp_path)
        assert fetcher._load_pre_unification_raw_store_skeleton(42) is None
